services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        # or set shared memory limit when deploy via swarm stack
        volumes:
            - type: tmpfs
              target: /dev/shm
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: ats_db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
